export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const ERROR_REGISTER = 'ERROR_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const LOGOUT = 'LOGOUT'
export const TOKEN = 'TOKEN'
export const ERROR_TOKEN = 'ERROR_TOKEN'